### ISSUE TITLE
ERROR: 2017/01/03 13:07:48 pygments.go:111: Error: no lexer for alias 'Markdown' found

### ISSUE THREAD

**Issue by pat-s** [ArjenSchwarz/wercker-step-hugo-build#31] opened 2017-01-03 13:17 UTC
Building works on localhost. When building on wercker, build is failing with `ERROR: 2017/01/03 13:07:48 pygments.go:111: Error: no lexer for alias 'Markdown' found`

`config.toml`: 
```toml
# Syntax Highlighting 
PygmentsCodeFences = true
pygmentsstyle = "emacs"
```

When building on wercker, build is failing with `ERROR: 2017/01/03 13:07:48 pygments.go:111: Error: no lexer for alias 'Markdown' found`

`Wercker.yml`:

```yml
box: golang:latest

build:
  steps:
    - add-to-known_hosts:
        hostname: github.com
        type: rsa
    - script:
        name: initialize and update git submodules
        code: |
            git submodule init
            git submodule update --remote --recursive
    - arjen/hugo-build:
        version: "HEAD"
        theme: academic
```

**Comment by ArjenSchwarz** [comment] 2017-01-03 22:08
Thanks for letting me know about this. I'll look into it later. As you're using an unstable version of Hugo, I'll just ask a couple of questions that might be able to help me.
* Did you try your working local build with the exact same commit of Hugo? This is just to verify that a change in Hugo didn't break something as it's usually not recommended to build from head for that reason.
* Can you provide me with the complete output of the build process in Wercker?
* If not, can you tell me which Hugo commit was used for the build? It should show up in the logs at some point.

Thanks

**Comment by pat-s** [comment] 2017-01-03 22:19
Local build worked fine. The error only occured when building on `wercker`. I think I also used the stable Hugo version before. 

See [here](https://app.wercker.com/pat-s/Website/runs/build/586ba1f8bbb613010045d402?step=586ba1fcd9da8c00016c1089) for the wercker build process.

**Comment by ArjenSchwarz** [comment] 2017-01-03 23:07
Thank you, that should help finding the problem. I'm at work currently, but I'll have a look tonight to see what I can find.

**Comment by ArjenSchwarz** [comment] 2017-01-04 12:10
Hi @pat-s, I've been looking into this. I noticed that you managed to get it working by changing the filenames to .md, so I tested with a version of your site before you did so.

Testing it locally by running the step from a docker container with everything set as it should be didn't give me any problems though. I figured at first that it might be an issue with pygments being an old version, so the latest build of the step that I just released has the ability to install it from python when an appropriate container is used (this obviously won't work with HEAD builds unless you install python and pip onto the golang container.

If you're ok with it, tomorrow I'll give it a try by cloning your website on Github and running it on Wercker itself (build only of course).

**Comment by pat-s** [comment] 2017-01-04 12:38
@ArjenSchwarz Thanks for your time! The .md filename changes in the latest builds were related to other issues.

I just looked into it again. In all builds, when `PygmentsCodeFences = true` in `config.toml` the builds failed. After I set it to `false`, `hugo build` succeeded. 

Check the [commit history](https://github.com/pat-s/Website/commits/master) of my repo. 
Until Commit `251d25834866aa975e9f6f376721182b1c2e437e` (commit message: `wercker.yml update`) all previous build attempts failed with the error mentioned above. 
In some attempts I also used version = "0.17" and not "HEAD", check the commit history with the red crosses before `wercker.yml update`.

The problem is that if I set `PygmentsCodeFences = false`, syntax highlighting is not performed the way it want it in my posts. Thats why I changed to use `highlight.js` to perform syntax highlighting ([see Hugo docs](https://gohugo.io/extras/highlighting/)) in my current setup and do not use `pygments` anymore. 

So the issue is not urgent for me anymore. Nevertheless the build problem using `pygments` should be solved or at least investigated :) Feel free to fork, build and investigate my wercker history!

**Comment by ArjenSchwarz** [comment] 2017-01-05 06:21
@pat-s I'm glad to hear that it isn't an issue for you anymore, and I could finally reproduce the error locally. 

However, I suspect that it's actually an issue with pygments itself. According to their site, they don't have a Markdown lexer, so the error message makes sense for a default installation of pygments. Is it possible that on your local machine you use an additional extension for that support? I noticed there is at least one of those around in https://github.com/jhermann/pygments-markdown-lexer

**Comment by ivanoats** [comment] 2017-02-02 17:32
FWIW, I had this issue when using python 2 `pip install Pygments` but when I did `pip3 install Pygments` the issue went away.  On MacOS using Homebrew.

**Comment by ArjenSchwarz** [comment] 2017-02-14 00:22
@ivanoats thanks for the information. I'll try to see if that will solve the issue

**Comment by sdebruyn** [comment] 2017-02-23 09:40
You could try with my docker image: https://github.com/SamuelDebruyn/docker-hugo-build
It has hugo and pygments installed. When I've got some time, I'll try to add compression libraries as well so you can minify your files on build.

**Comment by ArjenSchwarz** [comment] 2017-02-24 08:42
Ok, I've tried running the failing code with Python 3 as well as with SamuelDebruyn's Docker image. Neither solution worked for this exact test case. I stand by my original conclusion that this is because Pygments doesn't have a lexer called 'Markdown'. The only other reason I can think of is a difference in default lexers installed on MacOS vs Linux, but the Pygments website doesn't show a Markdown lexer either so that is less likely than it just not being available.
As pat-s went for a different solution it is also not an actual problem anymore and so I'm closing this issue.

Thank you all for your suggestions and help in trying to figure out this problem.

**Closed as completed by ArjenSchwarz** 2017-02-24 08:42 UTC
